name: Release Action Docker

on: 
  push:
    tags:
    - 'v**'

jobs:

  build:
    name: Release Action Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set DOCKER_REPO_NAME env 
      run: echo DOCKER_REPO_NAME=$(basename ${GITHUB_REPOSITORY}) >> ${GITHUB_ENV}
    - name: Set IMAGE_TAG env 
      run: echo IMAGE_TAG=$(basename ${GITHUB_REF}) >> ${GITHUB_ENV}
    - name: Append latest for each release
      run: echo IMAGE_TAG=${IMAGE_TAG},latest >> ${GITHUB_ENV}
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0
    
    - name: Build & Publish to Github Container Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: ${{ github.actor }}/${{ env.DOCKER_REPO_NAME }}
        username: ${{ github.actor }}
        password: ${{ secrets.PUSH_TOKEN }}
        platforms: linux/amd64
        registry: ghcr.io
        snapshot: false
        tags: "${{ env.IMAGE_TAG }}"

